
{{- define "svc.serviceaccount.tpl" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inventory.serviceAccountName" . }}
  labels:
    app: {{ template "svc.name" . }}
    release: {{ .Release.Name | quote }}
  annotations:
{{- end -}}
{{- define "svc.serviceaccount" -}}
{{- template "svc.util.merge" (append . "svc.serviceaccount.tpl") -}}
{{- end -}}
