# Default values for inventory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:32000/inventory
  pullPolicy: IfNotPresent
  port: 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: inventory

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 31000

ingress:
  enabled: false
