apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: inventory
  name: inventory
spec:
  ports:
  - port: 8080
    nodePort: 31000
    name: http
  selector:
    run: inventory
  type: NodePort
status:
  loadBalancer: {}
