Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "data/", "/home/vagrant/data"
  config.vm.network "public_network", ip: "192.168.0.17" 

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
end
